<a href="https://colab.research.google.com/github/Manawariqbal/Data-science-code/blob/main/Modeltuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/loan_approval_dataset.csv')
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [3]:
df=df.drop('loan_id',axis=1)

In [5]:
df
df.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [6]:
df.isnull().sum()

no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [7]:
df.drop_duplicates()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [11]:
X=df.drop(' loan_status',axis=1)
y=df[' loan_status']

In [14]:
X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000

In [18]:
#encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [17]:
df[' education'].value_counts()

 education
Graduate        2144
Not Graduate    2125
Name: count, dtype: int64

In [20]:
X[' education']=le.fit_transform(X[' education'])

In [21]:
X

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,1,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,0,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,0,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,1,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000
...,...,...,...,...,...,...,...,...,...,...,...
4264,5,0,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000
4265,0,1,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000
4266,2,1,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000
4267,1,1,No,4100000,12800000,8,780,8200000,700000,14100000,5800000
4268,1,0,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000

In [22]:
X[' self_employed']=le.fit_transform(X[' self_employed'])

In [23]:
X

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000
...,...,...,...,...,...,...,...,...,...,...,...
4264,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000
4265,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000
4266,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000
4267,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000
4268,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000

In [26]:
#Train test splitting
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
#scaling
from sklearn.preprocessing import StandardScaler
X_train_scaled=StandardScaler().fit_transform(X_train)
X_test_scaled=StandardScaler().fit_transform(X_test)

In [29]:
X_train_scaled

array([[ 1.51250774,  1.00263891, -1.01504731, ...,  2.04678575,
         0.07808278,  1.16041374],
       [-1.43500078,  1.00263891,  0.98517575, ...,  1.22311091,
         2.49843196,  0.88201987],
       [-0.84549907, -0.99736803, -1.01504731, ..., -0.8818359 ,
        -1.33923881, -1.31419838],
       ...,
       [ 0.92300603,  1.00263891,  0.98517575, ...,  1.29175048,
         1.47359943,  0.13963624],
       [-0.25599737,  1.00263891,  0.98517575, ..., -0.83607619,
         0.50327926,  1.4388076 ],
       [ 0.92300603, -0.99736803, -1.01504731, ..., -0.28695963,
         1.03750048, -0.10782497]])

In [39]:
#SVM
#svm model
from sklearn.svm import SVC
svc_model=SVC(C=3.0, kernel='rbf')
svc_model.fit(X_train_scaled,y_train)


#prediction
y_pred=svc_model.predict(X_test_scaled)




#Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)


#Manual tuning we do it manuanlly

#Grid search
from sklearn.model_selection import GridSearchCV

classifier=GridSearchCV((svc_model),
                      {
                          'C':[1,10,20,30],
                          'kernel':['rbf','linear']
                      },
                        cv=5,
                        return_train_score=False
                        )



classifier.fit(X_train_scaled,y_train)

GridSearchCV(cv=5, estimator=SVC(C=3.0),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [41]:
results=pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.177582,0.062403,0.047759,0.020647,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.932650,0.923865,0.941435,0.939971,0.945827,0.936750,0.007714,4
1,0.099355,0.003394,0.013350,0.000379,1,linear,"{'C': 1, 'kernel': 'linear'}",0.916545,0.913616,0.938507,0.925329,0.941435,0.927086,0.011242,5
2,0.095385,0.007119,0.022272,0.000491,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.937042,0.932650,0.960469,0.954612,0.957540,0.948463,0.011356,1
3,0.306872,0.022488,0.015186,0.003840,10,linear,"{'C': 10, 'kernel': 'linear'}",0.915081,0.912152,0.939971,0.925329,0.942899,0.927086,0.012540,5
4,0.105424,0.011561,0.021434,0.000547,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.938507,0.935578,0.957540,0.951684,0.953148,0.947291,0.008637,2
5,0.484474,0.045691,0.015254,0.004188,20,linear,"{'C': 20, 'kernel': 'linear'}",0.915081,0.912152,0.939971,0.925329,0.942899,0.927086,0.012540,5
6,0.110019,0.014004,0.023355,0.006879,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.937042,0.932650,0.950220,0.954612,0.948755,0.944656,0.008355,3
7,1.373867,0.205288,0.029820,0.008672,30,linear,"{'C': 30, 'kernel': 'linear'}",0.915081,0.912152,0.939971,0.925329,0.942899,0.927086,0.012540,5

In [43]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.936750
1        1       linear         0.927086
2       10          rbf         0.948463
3       10       linear         0.927086
4       20          rbf         0.947291
5       20       linear         0.927086
6       30          rbf         0.944656
7       30       linear         0.927086

In [45]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled,y_train)


#pred
y_pred=knn_model.predict(X_test_scaled)


#accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.892271662763466

In [46]:
knn_classifier=GridSearchCV((knn_model),
                      {
                          'n_neighbors':[3,5,7,9,11]
                      },
                        cv=5,
                        return_train_score=False
                        )

In [47]:
knn_classifier.fit(X_train_scaled,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 11]})

In [50]:
results=pd.DataFrame(knn_classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.021685,0.002501,0.094925,0.015809,3,{'n_neighbors': 3},0.869693,0.884334,0.926794,0.885798,0.871157,0.887555,0.020693,4
1,0.015049,0.005842,0.064169,0.021000,5,{'n_neighbors': 5},0.866764,0.891654,0.896047,0.887262,0.896047,0.887555,0.010894,4
2,0.016030,0.004554,0.077283,0.012932,7,{'n_neighbors': 7},0.874085,0.893119,0.909224,0.890190,0.909224,0.895168,0.013180,3
3,0.012872,0.003035,0.059168,0.015429,9,{'n_neighbors': 9},0.878477,0.890190,0.913616,0.903367,0.910688,0.899268,0.013174,2
4,0.011694,0.005765,0.069992,0.029454,11,{'n_neighbors': 11},0.885798,0.897511,0.915081,0.903367,0.928258,0.906003,0.014594,1

In [52]:
results[['param_n_neighbors','mean_test_score']]

   param_n_neighbors  mean_test_score
0                  3         0.887555
1                  5         0.887555
2                  7         0.895168
3                  9         0.899268
4                 11         0.906003

In [54]:
#Random search cv
from sklearn.model_selection import RandomizedSearchCV

random_cv_classifier=RandomizedSearchCV(estimator=knn_model,
                                        param_distributions={
                                            'n_neighbors':[3,5,7,9,11]
                                        },
                                        cv=5,
                                        n_iter=5,
                                        return_train_score=False
                                        )

random_cv_classifier.fit(X_train_scaled,y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=5,
                   param_distributions={'n_neighbors': [3, 5, 7, 9, 11]})

In [55]:
results=pd.DataFrame(random_cv_classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010334,0.001041,0.041453,0.003201,3,{'n_neighbors': 3},0.869693,0.884334,0.926794,0.885798,0.871157,0.887555,0.020693,4
1,0.011157,0.002876,0.057487,0.021564,5,{'n_neighbors': 5},0.866764,0.891654,0.896047,0.887262,0.896047,0.887555,0.010894,4
2,0.020672,0.005879,0.081424,0.029125,7,{'n_neighbors': 7},0.874085,0.893119,0.909224,0.890190,0.909224,0.895168,0.013180,3
3,0.018459,0.004664,0.102712,0.009074,9,{'n_neighbors': 9},0.878477,0.890190,0.913616,0.903367,0.910688,0.899268,0.013174,2
4,0.020246,0.005236,0.106707,0.017673,11,{'n_neighbors': 11},0.885798,0.897511,0.915081,0.903367,0.928258,0.906003,0.014594,1